### ISSUE TITLE
Remove personalizations

### ISSUE THREAD

**Issue by glynnw** [campDevs/DiscordBot#10]
Remove stuff like
https://github.com/campDevs/DiscordBot/blob/4beee3969bffa416f97dc09bf3c8f9aa6dc196ef/src/bot.js#L34

**Comment by pahosler** [comment]
keep the Bender ascii, I like it! Set activity to something like
 bot.user.setActivity(`Serving ${bot.guilds.size} servers`)

**Comment by glynnw** [comment]
We could also allow customization of that with a command or even a way for the user to specify.

**Comment by jodylecompte** [comment]
I agree Bender should stay, it suits the whole "We're gonna build our own bot, with blackjack!"

But this does pose an interesting question, what do we want to call it?

**Comment by glynnw** [comment]
I created two new issues for the bot name and implementing a command w/ a better default activity.
