### ISSUE TITLE
Change the description on the readme so that it is clear the bot is general purpose

### ISSUE THREAD

**Issue by glynnw** [campDevs/DiscordBot#104]
The description on the `README.md` would have someone believe the bot is only intended for the UFCC discord and not general purpose. I'm proposing we change the wording so that it instead says something like "in use on UFCC discord" instead "for UFCC's discord". Maybe even state specifically that it is general purpose.

**Comment by Azbo400** [comment]
I can look into this. I can change up the wording so it makes it clear that it is general purpose and could be used for any chat room, and it is use on the FCC chat in specific.

**Comment by Azbo400** [comment]
Fixed up everything in the pull request so I closed it
