### ISSUE TITLE
Move server specific features into a separate repo

### ISSUE THREAD

**Issue by glynnw** [campDevs/DiscordBot#11]
To make the bot more general purpose maybe we should move stuff that is specific to FCC and similar to another repo or something. What do you think?

**Comment by pahosler** [comment]
I'm not sure we'd have to do that, how about just a sub folder or a module naming convention for fcc related bots, like ufccBot-help-challenge.js

**Comment by glynnw** [comment]
Well if we want to generalize the bot and others come along then there will be features that make less sense for them.

**Comment by glynnw** [comment]
Well this could be something to consider later if flesh out a command plugin system or something. We could break the FCC stuff into a plugin or something.

**Comment by glynnw** [comment]
Closing and we can revisit it later if we want.
