### ISSUE TITLE
Add a contributing section or document and linting

### ISSUE THREAD

**Issue by glynnw** [campDevs/DiscordBot#12]
We need to agree on how to go about contributions.

**Comment by pahosler** [comment]
here's an idea, let's get someone to contribute something. I'll see if I can rewrite my horoscope to work with commando (I don't think it will take long) and submit a pull-request. Also maybe we should look at other's contrib readmes for details

**Comment by glynnw** [comment]
I meant more along the lines of linting and style guidelines, workflow, and how we go about accepting pull requests. Also do we want merges or rebasing? Do we want to have a dev branch and leave master production ready? Stuff like that.

**Comment by Azbo400** [comment]
Going to close this since I added the contributing section.
