### ISSUE TITLE
MDN command

### ISSUE THREAD

**Issue by jodylecompte** [campDevs/DiscordBot#16]
I have prototypal code for calling documentation from MDN and want to run it past everyody before coding up a final copy. 

Currently since MDN does not expose an API that I am aware of, the code I've written already works by doing a google search for a keyword and/or phrase locke down to the MDN domain, and then returns the first result as an embed.

Is this satisfactory? If not, does anyone have any ideas for a better implementation?

**Comment by glynnw** [comment]
Sounds reasonable. :+1:

**Comment by jodylecompte** [comment]
Here is an example of the output:
![Screenshot](https://s17.postimg.cc/59jqwjkr3/Screenshot_from_2018-05-05_13-40-20.png)
