### ISSUE TITLE
Cat-us code

### ISSUE THREAD

**Issue by jodylecompte** [campDevs/DiscordBot#21]
Catuscode is a command I implemented around https://http.cat/ (a cat for every HTTP status code). The functionality is very simple, you use `catuscode 500` for example and it displays the following:
![500 Code](https://http.cat/500)

Part of me thinks it's a goofy feature, I implemented it because I was basically working down a list of free APIs to play with, but on the same, in the discord channel we do have occasional questions like Why is my API call returning status code 301 and cat-pictures always help to stick in peoples memory. The box model explained with cats sleeping in a box comes to mind.

What do y'all think? Is there any value in porting this over?

**Comment by jodylecompte** [comment]
We could also link to https://developer.mozilla.org/en-US/docs/Web/HTTP/Status for more in depth information on each code along with the cat picture.

**Comment by glynnw** [comment]
Both seem like great ideas. :+1:

**Comment by pahosler** [comment]
Love it!
