### ISSUE TITLE
Rollem / Rickroll

### ISSUE THREAD

**Issue by jodylecompte** [campDevs/DiscordBot#23]
Do we want to add rickroll? I don't have any personal feelings, but it was one of the staple functions of Camperbot along with 8ball that got used semi-regularly. 

We could rate limit it to keep anyone from being (overly) annoying.

**Comment by glynnw** [comment]
I've a roll command already in the bot but it is just a sketcy looking embed that links to the rick astley video. @Azbo400 I think is looking to make an improved version.

**Comment by Azbo400** [comment]
Yeah we could probably try to limit the amount of times someone calls it and control the embeds so it doesn't flood the chat.

**Comment by glynnw** [comment]
Commando has built in rate limiting and is pretty straight forward so no worries there.

**Comment by Azbo400** [comment]
Yep that should be pretty quick to add we just have to agree on the intervals (how much it could be called in a specific amount of time). I will assign myself to this for now.

**Comment by Azbo400** [comment]
Closed because it was added in pull request #32
