### ISSUE TITLE
Add command that directs users to file issues here

### ISSUE THREAD

**Issue by glynnw** [campDevs/DiscordBot#25]
We should add a command to the bot to file issues and send them directly to a new issue. We should also make the command discoverable and the user aware it exists somehow. Maybe a message in the help command or such.

**Comment by pahosler** [comment]
the github API should make that easy enough, but what would keep people from just being bored and and sending a crap ton of issues via the bot?

I still like my idea of sending a PM to the module dev if the bot encounters an error. I don't think it would be as horrible in the scenario you described where someone might take an advantage of an error and send a bunch of PM's. I would announce publicly that that is happening anyway. Also if you are getting a too many PMs from a failing module that would hopefully encourage you to fix the issue faster. Worse case you don't give a crap and turn off the messages for the error that's being generated.

**Comment by pahosler** [comment]
oh maybe I misunderstood... just have a link the user can click on that brings them to the issue page. That would be better, yes

**Comment by Azbo400** [comment]
So maybe a command such as `issue` or something that can then give a message saying where the user can file an issue so the user can then click a link to submit a new issue? 

For example: 
`@bot issue`

bot:
`click here to file an issue *link*`
I can make that if so probably.
