### ISSUE TITLE
Add Help Command

### ISSUE THREAD

**Issue by Azbo400** [campDevs/DiscordBot#26]
I am thinking we should maybe add a help command to list all the commands you can give the bot as well as provide info on a specific command so someone can call it correctly. What do you guys think? 

Examples can include: 
`@bot help`
*lists commands*

`@bot help __________<---command here`
*lists info on command*

**Comment by glynnw** [comment]
There is a built in help command. Commando provides that for free.

**Comment by glynnw** [comment]
I'm closing as it already exists
