### ISSUE TITLE
Provide a command to change the activity (playing game status) and a better default

### ISSUE THREAD

**Issue by glynnw** [campDevs/DiscordBot#30]
@pahosler mentioned changing the default status to show how many servers and such. We should also have a command to change it to something else.

**Comment by pahosler** [comment]
you could have some canned status messages and set custom messages
+status server-count
+status telling-jokes
+status /get brownie points now!/  (custom status)

**Comment by joker314** [comment]
I'll work on this one.

```
+status %count%
+status In %count% servers
+status Being a typical, obedient, bot
```

However, what permission level should somebody have in order to use the command? Manage bots?
