### ISSUE TITLE
Better bot name

### ISSUE THREAD

**Issue by glynnw** [campDevs/DiscordBot#31]
Lets try to list ideas for a bot name here and decide on a better name.

**Comment by pahosler** [comment]
since this is West World night my first choice is...

Dolores

alternate choice

Campy

**Comment by jdraiv** [comment]
I approve Campy 👍

**Comment by Azbo400** [comment]
+1 Campy

**Comment by glynnw** [comment]
:+1: Dolores myself. Campy is too campy :P

**Comment by glynnw** [comment]
Also remember that you can have the name be anything you want in the server. So we could name the bot DoloresBot and campy on the discord.

**Comment by Azbo400** [comment]
Yeah I agree but I don't want too much confusion if their is seperate names between the GitHub and actual name

**Comment by pahosler** [comment]
bitterButterBattleBot

**Comment by glynnw** [comment]
Seems like it is going to be called campy. @campDevs/discordbot Any more suggestions?

**Comment by pahosler** [comment]
maybe one more blind vote in #general chat with some decent names peppered into the mix?
