### ISSUE TITLE
@Devs - please read

### ISSUE THREAD

**Issue by pahosler** [campDevs/DiscordBot#34]
Let's start adding better titles to the issues. Maybe prefixes like:
@campDevs/discordbot
Important!
Feature
News
Bugs
etc.

This will help keep things organized and help with getting each other's attention.

Another nice thing would be acknowledging a posted issue. Especially if there is a title that mentions the group.

If you see an issue that you would like to tackle, assign yourself to it and move it out of the inbox (maybe this is something you don't see if you aren't using waffle.io?) 

Add tags to your issue, there is probably already an appropriate tag in the list. 

These are just suggestions to make things a tad more helpful. Things are already getting busy with three or four active people. If this grows at all a little organization will go a long way.

**Comment by glynnw** [comment]
Instead of having an open issue for this we should add something to contributing. Also instead of `@devs` use `@campDevs/discordbot` as it will tag the bot team. Also, the important!, feature, and etc - seem like labels.

**Comment by Azbo400** [comment]
I edited the tag so it notifies all the contributors. I can also go through and add this too the contributing section of the readme.
