### ISSUE TITLE
@Devs Add config.json to .gitignore and create a config.json template

### ISSUE THREAD

**Issue by pahosler** [campDevs/DiscordBot#35]
if you're like me, you've probably changed to command prefix so you can run your dev bot in a channel with other dev bots. We don't want to push a change to the production bot's config.json

**Comment by glynnw** [comment]
:+1: However, the defaults probably should stay in version control as default.config.json or something then defer to the overrides in config.json. Or we could hard code it in in the bot if there is some upside to doing that. The goal is to keep the defaults from being strewn through out the bot and centralized.

**Comment by pahosler** [comment]
just figured out you can't use .gitignore for this. It won't ignore files that are already tracked. I'm not sure of a workaround, yet.

**Comment by pahosler** [comment]
I suppose for the time being, if you change the prefix in your fork, change it back to "+" before pushing your code to your fork, annoying but doable.

**Comment by glynnw** [comment]
You can remove it. Just remove the file from the cache using `git rm --cached config.json`

**Comment by Azbo400** [comment]
Yeah I just changed it before I committed it, could we maybe make it so you put in your prefix the .env file and set a default if they don't?
