### ISSUE TITLE
Add cli prompt that accepts a token and generates url to add bot to server/guild

### ISSUE THREAD

**Issue by pahosler** [campDevs/DiscordBot#5]
needed: someone to research the ability to automate discord bot registration. This is NOT a priority, but simply a project to help fast track new devs. If automation isn't possible, then clear and easy to follow instructions with screenshots would be helpful.

**Comment by glynnw** [comment]
I think it would be sufficient to just do the later. Clear instructions on how to create a bot account and add it to a server. Also we could streamline the token process by having a prompt on the cli ask for the token and store it for them. Additionally it could generate or spit out the url to add the bot to the server.

**Comment by pahosler** [comment]
I like that!

**Comment by pahosler** [comment]
Closed: See How to: Create bot account

**Comment by glynnw** [comment]
I'm reopening it and changing the title instead of creating a new issue.

**Comment by glynnw** [comment]
Or nm you created a new issue already.
