### ISSUE TITLE
simple website/blog

### ISSUE THREAD

**Issue by pahosler** [campDevs/DiscordBot#6]
this is a small group now, so this is a back burner issue, in other words I'm just seeding ideas for future projects. 
Create a forward facing page describing our project and possibly bot development in general. We've already done some interesting things, let's talk about them!

**Comment by jodylecompte** [comment]
How would y'all feel about a static site generator? Namely either Jekyll or Gatsby? I'd rather Gatsby personally, but people tend to be more familiar with Jekyll by means of Github pages.

**Comment by Azbo400** [comment]
I think a static site generator would be useful as it would be easy to set up and maintain. I also prefer Gatsby and React however I am fine if Jekyll is the way we go if people are more familiar with it shouldn't take me too long to learn it.

**Comment by glynnw** [comment]
I'm down with any of those choices. But since the project is JS I lean towards Gatsby.

**Comment by glynnw** [comment]
I created campDevs/campDevs.github.io repo under the org. I think I'm going to close this issue and open one there to discuss the site generator.

**Comment by glynnw** [comment]
Vote at campDevs/campDevs.github.io#1
