### ISSUE TITLE
Add security.txt file

### ISSUE THREAD

**Issue by joker314** [campDevs/DiscordBot#80]
# 🗺 Overview

Security is *really* important. We already have a contact email for code-of-conduct violations. We're now using it for security vulnerability reporting too, I guess. Now, we need to add this email to a standardised file so that tools that security researchers might use can pick up on it (also, so that security researchers who are looking can easily find this contact email)

# 📚 Description

This is the email:

```
septimus98@gmail.com
```
It needs to be added to a new file called `.security.txt` which [should](https://tools.ietf.org/html/draft-foudil-securitytxt-04#section-4.2) be in the top-level directory (that is, it shouldn't be in any folders)

This file should look like this:

```
# Reach out to this email and we will look into the issue as soon as we can.
Contact: mailto:septimus98@gmail.com
```

# 📂 Relevant files

- `.security.txt` (**new**)

# 🔗 Find out more

About security.txt

- 🔒 [Website](https://securitytxt.org)
- 💬 [**Draft** RFC (Request for Comments)](https://tools.ietf.org/html/draft-foudil-securitytxt-04)
- 💻 [Github Repository](https://github.com/securitytxt/security-txt)

**Comment by beatriceo** [comment]
Hi, I'd like to take care of this issue! (This would be my first contribution)

**Comment by joker314** [comment]
@beatriceo Go ahead! If you need any help, please feel free to ask.

**Comment by beatriceo** [comment]
Hi, it seems that I don't have access.

<img width="656" alt="screen shot 2018-07-29 at 11 56 30 pm" src="https://user-images.githubusercontent.com/31216493/43371496-249f8dbe-938b-11e8-95df-bece1b4d5b20.png">

**Comment by joker314** [comment]
@beatriceo That's right! You need to push to your fork (https://github.com/beatriceo/DiscordBot)

Try

```
git remote set-url origin https://github.com/beatriceo/DiscordBot.git/
```

Then, you may run the `git push` command to push this to your fork.

After that, you'll need to go to the GitHub online interface in order to create a pull request. 🙂

**Comment by Azbo400** [comment]
@beatriceo You cannot push directly to the repo, you are required to fork the repository and then push your changes in a new branch then open a pull request comparing the forked branch to the actual repo that we will than merge if it is approved. 

Here is some links to fork the repo and open a pull request: 
https://blog.scottlowe.org/2015/01/27/using-fork-branch-git-workflow/
https://help.github.com/articles/creating-a-pull-request-from-a-fork/

**Comment by glynnw** [comment]
@beatriceo Thanks for the contribution!
