### ISSUE TITLE
"good first issue" brainstorm needed

### ISSUE THREAD

**Issue by joker314** [campDevs/DiscordBot#82]
We need to come up with issues that those who are new to open source may find accessible. In particular, certain events, such as "Hacktoberfest", encourage users to make pull requests to FOSS.

Does anyone have any ideas? Perhaps easy-to-add commands? Or, perhaps textual changes to documentation (personally, that's a 👎 idea from me because it doesn't immerse users into FOSS as much (albeit such changes are vital to FOSS).

How about timezone converters? Etc.

In addition, how about we add a special section for new contributors to the CONTRIBUTING file, which clearly explains how to make commands in an easy-to-understand manner? (Please mark such pull requests as "Towards #81" rather than "Resolves #81")

**Comment by joker314** [comment]
Proposing #9 for good-first-issue?

**Comment by pahosler** [comment]
In response to "how to make commands", we could create a command-template.js or several versions of it that do specific types of things. Like multi level or single level commands, for example. Basically a template or skel file might be very helpful.

**Comment by joker314** [comment]
Yep, that works. We could link to this in every good-first-issue that requires adding a command, as well as at the beginning of the CONTRIBUTING file.

Let's make a directory "commando-examples" to do this.

Do you wish to work on this?

**Comment by joker314** [comment]
I see no substantial additions, let's track @pahosler's suggestion in #85
