### ISSUE TITLE
Add self-assignable pronoun roles

### ISSUE THREAD

**Issue by joker314** [campDevs/DiscordBot#83]
# 🗺 Overview

This is a `good first issue`. It's been specially made for newer contributors to open source; or new contributors to this repository, to start out.

You'll want to be familiar with the popular chat platform [Discord](https://discordapp.com) -- and create a server there to test your bot. Then, you can create a bot, bot token, invitation link, and fill in the environment file, by following along our [Contributing](https://github.com/campDevs/DiscordBot/blob/master/CONTRIBUTING.md) file.

Make sure to give your bot a role with adequate permissions so that it can give other users roles. That's important for this issue.

**Remember: we're here to help**. Your first contributions will likely be hard (either to open source; or to this repository). But we're really bored and are willing to spend a lot of time to guide you.

# 💡 Description

Your task is to add a command `pronoun` that will allow users to self-assign themselves a limited set of roles. An example of the syntax of this command is given below

```
-pronoun add she
```
Your command should take two arguments. The first will be the action the user wants to take.

- `add` ; `a`
- `remove` ; `r`

On start-up, your file should read from a JSON file in the `src/utils` directory. You should make this file in your pull request, and give it the following text:

```json
[
  {"aliases": ["he", "his", "him"], "roleName": "he/him"},
  {"aliases": ["she", "her", "hers"], "roleName": "she/her"},
  {"aliases": ["they", "their", "theirs", "them"], "roleName": "they/them"},
]
```

The code you write should

- Read from the JSON file 
- If a user asks for something in an `aliases` field, check if the role specified in `roleName` exists
- If so, assign the user that role. If not, show an error message to the user.

If the user does `pronoun remove` rather than `pronoun add`, in the last step you should remove the role from the user.

ProTip: you can `require()` in a JSON file and it will automatically get parsed as JS object
ProTip: look at [other pieces of code](https://github.com/campDevs/DiscordBot/tree/master/src/commands) that create commands
ProTip: The `msg` argument you get when responding to commands [is documented](https://discord.js.org/#/docs/main/stable/class/Message) and you might find `guild` interesting (it represents a server). This is quite hard, though, so please do ask if you get stuck!

# 📑 Resources

- [Our Contributing file](https://github.com/campDevs/DiscordBot/blob/master/CONTRIBUTING.md) could help you get a bot set up
- [Discord](https://discordapp.com), the chat platform
- [`src/commands`](https://github.com/campDevs/DiscordBot/tree/master/src/commands)
- GitHub's [guide](https://help.github.com/articles/fork-a-repo/) on forking repositories

# 📂 Files you need to change

- <code><a href="https://github.com/campDevs/DiscordBot/tree/master/src/utils">src/utils</a>/pronouns.json</code> **new** (the JSON file)
- <code><a href="https://github.com/campDevs/DiscordBot/tree/master/src/commands/assistants">src/commands/assistants</a>/Pronouns.js</code> **new** (your code)

**Comment by joker314** [comment]
Due to inactivity, bumping this to "Help Wanted", so anyone can contribute. In 7 days, this will become a standard issue for the regular development team to take.

**Comment by joker314** [comment]
This has been open for public contribution for a while. Anyone object if I take this?

**Comment by glynnw** [comment]
As long as you don't find yourself needing a DB just yet then sure why not?
