### ISSUE TITLE
Magic 8 Ball

### ISSUE THREAD

**Issue by pahosler** [campDevs/DiscordBot#9]
"shake" the Magic 8 Ball and get a response to your life changing questions.

have options for
Classic Responses
Funny Responses
Sarcastic Responses
Mean "grumpy cat" Responses
Random Response from above responses

**Comment by jodylecompte** [comment]
Here are the standards you would find on a real magic 8-ball:
```
const phrases = [
  'It is certain',
  'It is decidedly so',
  'Without a doubt',
  'Yes definitely',
  'You may rely on it',
  'As I see it, yes',
  'Most likely',
  'Outlook good',
  'Yes',
  'Signs point to yes',
  'Reply hazy try again',
  'Ask again later',
  'Better not tell you now',
  'Cannot predict now',
  'Concentrate and ask again',
  'Don\'t count on it',
  'My reply is no',
  'My sources say no',
  'Outlook not so good',
  'Very doubtful'
]
```

Looking forward to Grumpy Cat versions.

**Comment by pahosler** [comment]
I have that in my go bot (the standard list). Thank you for posting them here too. If I write or, or anyone else for that matter, I'd like it to implement flat file/json response data. That way anyone can add response files into a directory and 8ball can load them.

**Comment by pahosler** [comment]
yeah, I think grumpy cat responses could be fun

**Comment by pahosler** [comment]
Jody are you working on this one?

**Comment by joker314** [comment]
I'd love to work on this if you don't mind, btw? Either way, work on branch `feature/command-8ball` and push and pull changes as soon as you commit.
